// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtUchoiMewtgC5BcpzgUxGbKw8ej-EC8',
    appId: '1:445477841853:web:48dd13c82b4bed7c2700d4',
    messagingSenderId: '445477841853',
    projectId: 'projeto-wund-app',
    authDomain: 'projeto-wund-app.firebaseapp.com',
    storageBucket: 'projeto-wund-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ABZW-ymIqSJfw7qs040Ta0kvI6jbqz0',
    appId: '1:445477841853:android:c2d36a98835ec79c2700d4',
    messagingSenderId: '445477841853',
    projectId: 'projeto-wund-app',
    storageBucket: 'projeto-wund-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMq652UHvCrqPKZ_w8iYMRrLyaIqWe0Q',
    appId: '1:445477841853:ios:904efa672c3a38722700d4',
    messagingSenderId: '445477841853',
    projectId: 'projeto-wund-app',
    storageBucket: 'projeto-wund-app.appspot.com',
    iosClientId: '445477841853-21vo2n8t6s8vj51j3156l88u5mjpgsm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wund',
  );
}
